// Generated by Wrangler by running `wrangler types` — update by running `npm run cf-typegen`
declare namespace Cloudflare {
	interface Env {
		MCP_OBJECT: DurableObjectNamespace<import("./src/index").MyMCP>;
		UPSTOX_ANALYTICS_TOKEN: string;
	}
}
interface Env extends Cloudflare.Env {}
